theme: minima
title: Usman Asif's Tech Journal
author:
  name: Usman Asif
  email: usman.asif2208@gmail.com
header_pages:
  - about.md

minima:
  skin: dark
 
  social_links:
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/usman-asif-ua2208/"
    - title: GitHub
      icon: github
      url: "https://github.com/usmanasifbutt"
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/usman.asif22/"

future: true